language: ruby
before-install: rvm use jruby-1.7.4 --install --binary --fuzzy
rvm:
#  - jruby-18mode
#  - jruby-19mode
  - jruby-head
jdk:
#  - openjdk6
  - openjdk7
#  - oraclejdk7
#language: java
#install: mvn prepare-package -Dmaven.test.skip -quiet
#script: mvn cucumber:test -Djruby.versions=1.5.6
#jdk:
#  - openjdk6
#  - openjdk7
