language: ruby
bundler_args: --without copyright
rvm:
  - jruby-18mode
  - jruby-19mode
  - jruby-head
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
matrix:
  include:
    - rvm: jruby
      script: mvn clean verify
